"""Reproducibility contract tests for SplitGuard-AD manifests.

The framework makes TWO contracts about split generation, and they pull in
opposite directions. Both must hold at once:

1. **Determinism** — the same ``--seed`` produces a byte-identical manifest
   across runs, machines and Python versions.
2. **Seed sensitivity** — a *different* ``--seed`` produces a *different*
   manifest, so that the reported seed-to-seed variability is real split
   variability and not merely training-time noise.

An earlier revision of this file tested only contract (1), and enshrined a
``(-n_images, component_id)`` sort key as the way to achieve it. That key is a
*total order on seed-independent fields*: it satisfies determinism by erasing
the seeded shuffle entirely, which silently violates contract (2). Under it,
all five ADNI "per-seed" manifests regenerated byte-identically and the
released manifests could no longer be reproduced at all (86-130 scans moved
per seed). The tests passed the whole time, because they never asked whether
different seeds gave different answers.

The generators now tie-break on ``_shuffle_rank`` — the component's index
after the seeded shuffle. That is an explicit integer key (so ordering does
not depend on sort stability or platform) that is nonetheless a function of
the seed (so different seeds diverge). The tests below pin down both halves.
"""

from __future__ import annotations

import csv
import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load_module(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[path.stem] = module
    spec.loader.exec_module(module)
    return module


def _ranked(sizes_and_ids):
    """Components carrying an explicit shuffle rank, as the generators supply."""
    return [
        {"component_id": cid, "n_images": n, "_shuffle_rank": rank}
        for rank, (n, cid) in enumerate(sizes_and_ids)
    ]


class BinPackingDeterminismTests(unittest.TestCase):
    """Contract 1: the bin-packer is a pure function of its inputs."""

    def test_current_choose_subset_is_deterministic(self):
        module = _load_module(ROOT / "scripts" / "make_current_splitguard_split.py")
        components = _ranked(
            [(30, "c_alpha"), (30, "c_beta"), (30, "c_gamma"), (20, "c_delta"), (10, "c_eps")]
        )
        first = module.choose_subset_by_size(components, 60)
        second = module.choose_subset_by_size(components, 60)
        self.assertEqual(first, second)

    def test_adni_choose_subset_is_deterministic(self):
        module = _load_module(ROOT / "scripts" / "make_adni_splitguard_split.py")
        components = _ranked(
            [(40, "adni_a"), (40, "adni_b"), (40, "adni_c"), (25, "adni_d"), (15, "adni_e")]
        )
        first = module.choose_subset_by_size(components, 80)
        second = module.choose_subset_by_size(components, 80)
        self.assertEqual(first, second)

    def test_adni_tie_is_broken_by_shuffle_rank_not_component_id(self):
        """Two equal-size components: the one the seeded shuffle put first wins.

        This is the regression lock. If a future refactor restores a
        ``component_id`` tie-break, this test fails — and it must, because
        that key makes the seed inert.
        """
        module = _load_module(ROOT / "scripts" / "make_adni_splitguard_split.py")
        # "adni_z" is lexicographically LAST but has rank 0, so it must be
        # selected. Under a component_id tie-break, "adni_a" would win instead.
        components = _ranked([(50, "adni_z"), (50, "adni_a"), (30, "adni_c")])
        chosen = module.choose_subset_by_size(components, target=50)
        self.assertEqual(
            chosen,
            {"adni_z"},
            "Ties must resolve on the seeded shuffle rank. Selecting 'adni_a' "
            "means the tie-break reverted to component_id, which imposes a "
            "seed-independent total order and makes every per-seed manifest "
            "identical.",
        )


class SeedSensitivityTests(unittest.TestCase):
    """Contract 2: different seeds must produce different splits.

    This is the half whose absence let the seed-inertness regression ship.
    """

    ADNI_COMPONENTS = ROOT / "data" / "manifests" / "adni" / "adni_leakage_components.csv"

    def _partition_map(self, path: Path) -> dict[str, str]:
        with path.open(newline="", encoding="utf-8") as handle:
            return {row["image_id"]: row["split"] for row in csv.DictReader(handle)}

    @unittest.skipUnless(
        ADNI_COMPONENTS.exists(),
        "ADNI component manifest not present locally (data/ is not redistributed).",
    )
    def test_adni_different_seeds_produce_different_splits(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmpdir = Path(tmp)
            subprocess.run(
                [
                    sys.executable,
                    str(ROOT / "scripts" / "make_adni_splitguard_split.py"),
                    "--seeds", "0", "1",
                    "--components", str(self.ADNI_COMPONENTS),
                    "--split-dir", str(tmpdir),
                    "--summary-dir", str(tmpdir),
                ],
                check=True, capture_output=True,
            )
            seed0 = self._partition_map(tmpdir / "adni_splitguard_seed0.csv")
            seed1 = self._partition_map(tmpdir / "adni_splitguard_seed1.csv")

        shared = set(seed0) & set(seed1)
        moved = sum(1 for key in shared if seed0[key] != seed1[key])
        self.assertGreater(
            moved,
            0,
            "Seeds 0 and 1 produced identical partitions. The seed is inert: "
            "reported seed-to-seed variability would reflect training noise "
            "only, not split variability.",
        )

    @unittest.skipUnless(
        ADNI_COMPONENTS.exists(),
        "ADNI component manifest not present locally (data/ is not redistributed).",
    )
    def test_adni_same_seed_reproduces_byte_identically(self):
        outputs = []
        for _ in range(2):
            with tempfile.TemporaryDirectory() as tmp:
                tmpdir = Path(tmp)
                subprocess.run(
                    [
                        sys.executable,
                        str(ROOT / "scripts" / "make_adni_splitguard_split.py"),
                        "--seeds", "0",
                        "--components", str(self.ADNI_COMPONENTS),
                        "--split-dir", str(tmpdir),
                        "--summary-dir", str(tmpdir),
                    ],
                    check=True, capture_output=True,
                )
                outputs.append((tmpdir / "adni_splitguard_seed0.csv").read_bytes())
        self.assertEqual(
            outputs[0], outputs[1],
            "Same seed produced different bytes across runs; the manifest is "
            "not byte-reproducible.",
        )


class ReleasedManifestFidelityTests(unittest.TestCase):
    """The released frozen manifests must be regenerable by the released code.

    This is the contract a reviewer exercises first: clone the repo, run the
    generator, and check that the splits the paper's numbers came from are the
    splits the code produces. It failed silently once already.
    """

    ADNI_COMPONENTS = ROOT / "data" / "manifests" / "adni" / "adni_leakage_components.csv"
    FROZEN_DIR = ROOT / "data" / "splits" / "adni"

    @unittest.skipUnless(
        ADNI_COMPONENTS.exists() and FROZEN_DIR.exists(),
        "ADNI manifests not present locally (data/ is not redistributed).",
    )
    def test_released_adni_manifests_regenerate_exactly(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmpdir = Path(tmp)
            subprocess.run(
                [
                    sys.executable,
                    str(ROOT / "scripts" / "make_adni_splitguard_split.py"),
                    "--seeds", "0", "1", "2", "3", "4",
                    "--components", str(self.ADNI_COMPONENTS),
                    "--split-dir", str(tmpdir),
                    "--summary-dir", str(tmpdir),
                ],
                check=True, capture_output=True,
            )
            for seed in range(5):
                name = f"adni_splitguard_seed{seed}.csv"
                frozen = self.FROZEN_DIR / name
                if not frozen.exists():
                    continue
                self.assertEqual(
                    frozen.read_bytes(),
                    (tmpdir / name).read_bytes(),
                    f"Regenerated {name} differs from the released manifest. "
                    "The published results cannot be reproduced from the "
                    "released code.",
                )


if __name__ == "__main__":  # pragma: no cover - convenience runner
    unittest.main()
