#!/usr/bin/env python3
"""Generate LaTeX tables for the ADNI section of the long paper.

Produces self-contained ``.tex`` snippets under ``paper/tables/`` that
the main manuscript can pull in with ``\\input{}``.

Tables generated
----------------
1. ``paper/tables/adni_inflation_gap.tex`` — protocol × {AUROC mean,
   95% CI, n_test, contamination} for the ADNI inflation-gap result,
   with-MT1 and without-MT1 side-by-side columns.
2. ``paper/tables/adni_demographics.tex`` — per-group {n_subjects,
   n_scans, age mean ± SD, sex %, education, MMSE} for CN / MCI / AD.

Inputs (already on disk)
------------------------
* ``reports/tables/adni/adni_inflation_gap_bootstrap.json``
* ``reports/tables/adni/adni_inflation_gap_no_mt1_bootstrap.json``
* ``data/manifests/adni/adni_manifest.csv``
* ``data/raw/adni/study_files/PTDEMOG_22May2026.csv``
* ``data/raw/adni/study_files/MMSE_22May2026.csv``

Outputs are simple ``tabular`` environments wrapped in ``table*`` so
the main paper can keep its own ``\\caption`` / ``\\label`` if it
prefers; both styles are documented inline.
"""

from __future__ import annotations

import csv
import json
import statistics
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = PROJECT_ROOT / "paper" / "tables"

BS_WITH_MT1 = PROJECT_ROOT / "reports" / "tables" / "adni" / "adni_inflation_gap_bootstrap.json"
BS_NO_MT1 = PROJECT_ROOT / "reports" / "tables" / "adni" / "adni_inflation_gap_no_mt1_bootstrap.json"
CSV_WITH_MT1 = PROJECT_ROOT / "reports" / "tables" / "adni" / "adni_inflation_gap.csv"
CSV_NO_MT1 = PROJECT_ROOT / "reports" / "tables" / "adni" / "adni_inflation_gap_no_mt1.csv"

MANIFEST = PROJECT_ROOT / "data" / "manifests" / "adni" / "adni_manifest.csv"
PTDEMOG = PROJECT_ROOT / "data" / "raw" / "adni" / "study_files" / "PTDEMOG_22May2026.csv"
MMSE = PROJECT_ROOT / "data" / "raw" / "adni" / "study_files" / "MMSE_22May2026.csv"


def fmt_ci(point: float, lo: float, hi: float) -> str:
    return f"{point:.3f} [{lo:.3f}, {hi:.3f}]"


def fmt_pm(point: float, sd: float, n: int = 3) -> str:
    return f"{point:.{n}f} $\\pm$ {sd:.{n}f}"


def load_bootstrap(path: Path) -> dict:
    return json.loads(path.read_text())


def per_seed_contam(csv_path: Path, protocol: str) -> tuple[float, float]:
    """Return mean and sd of test_subject_contamination_pct for a protocol."""
    rows = [r for r in csv.DictReader(csv_path.open()) if r["protocol"] == protocol]
    vals = [float(r["test_subject_contamination_pct"]) for r in rows]
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def per_seed_ntest_mean(csv_path: Path, protocol: str) -> float:
    rows = [r for r in csv.DictReader(csv_path.open()) if r["protocol"] == protocol]
    return statistics.mean(float(r["n_test"]) for r in rows)


def build_inflation_table() -> str:
    bw = load_bootstrap(BS_WITH_MT1)
    bn = load_bootstrap(BS_NO_MT1)

    def row(label: str, key: str, key_no_mt1: str = None) -> str:
        key_no_mt1 = key_no_mt1 or key
        w = bw["auroc"][key]
        n = bn["auroc"][key_no_mt1]
        contam_w_mean, contam_w_sd = per_seed_contam(CSV_WITH_MT1, key)
        ntest_w = per_seed_ntest_mean(CSV_WITH_MT1, key)
        contam_n_mean, contam_n_sd = per_seed_contam(CSV_NO_MT1, key_no_mt1)
        ntest_n = per_seed_ntest_mean(CSV_NO_MT1, key_no_mt1)
        return (
            f"  {label} & "
            f"{fmt_ci(w['point_mean'], w['ci_lo'], w['ci_hi'])} & "
            f"{ntest_w:.0f} & "
            f"{contam_w_mean:.1f}\\% & "
            f"{fmt_ci(n['point_mean'], n['ci_lo'], n['ci_hi'])} & "
            f"{ntest_n:.0f} & "
            f"{contam_n_mean:.1f}\\% \\\\"
        )

    g_w = bw["inflation_gap"]["total_random_minus_component_safe"]
    g_n = bn["inflation_gap"]["total_random_minus_component_safe"]
    sl_w = bw["inflation_gap"]["subject_leakage_random_minus_subject_only"]
    sl_n = bn["inflation_gap"]["subject_leakage_random_minus_subject_only"]
    cm_w = bw["inflation_gap"]["component_leakage_subject_only_minus_component_safe"]
    cm_n = bn["inflation_gap"]["component_leakage_subject_only_minus_component_safe"]

    body = "\n".join([
        "% Auto-generated by scripts/generate_adni_paper_tables.py.",
        "% Do not hand-edit; regenerate from the bootstrap JSONs.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{ADNI inflation gap, 5 seeds, 15 epochs, ResNet-18, coronal centre slice. "
        "Numbers are mean AUROC with paired-seed bootstrap 95\\% CI (B=10{,}000). "
        "``Test contamination'' = mean \\% of test subjects also appearing in the train partition. "
        "The MT1-excluded column drops the 28 magnetization-transfer T1 scans for a sequence-homogeneity sensitivity check.}",
        "\\label{tab:adni_inflation_gap}",
        "\\small",
        "\\begin{tabular}{lrrrrrr}",
        "  \\toprule",
        "   & \\multicolumn{3}{c}{\\textbf{All scans (incl. MT1)}} & \\multicolumn{3}{c}{\\textbf{MT1 excluded}} \\\\",
        "  \\cmidrule(lr){2-4} \\cmidrule(lr){5-7}",
        "  Protocol & AUROC [95\\% CI] & $n_{\\text{test}}$ & Test contam. & AUROC [95\\% CI] & $n_{\\text{test}}$ & Test contam. \\\\",
        "  \\midrule",
        row("Random (leaky)", "random"),
        row("Subject-only",   "subject_only"),
        row("Component-safe (\\textsc{SplitGuard})", "component_safe"),
        "  \\midrule",
        "  \\multicolumn{7}{l}{\\textit{Inflation-gap decomposition (paired bootstrap):}} \\\\",
        (
            f"  Total (random $-$ component-safe) & "
            f"{fmt_ci(g_w['point_estimate'], g_w['ci_lo'], g_w['ci_hi'])} & & & "
            f"{fmt_ci(g_n['point_estimate'], g_n['ci_lo'], g_n['ci_hi'])} & & \\\\"
        ),
        (
            f"  Subject-leakage (random $-$ subject-only) & "
            f"{fmt_ci(sl_w['point_estimate'], sl_w['ci_lo'], sl_w['ci_hi'])} & & & "
            f"{fmt_ci(sl_n['point_estimate'], sl_n['ci_lo'], sl_n['ci_hi'])} & & \\\\"
        ),
        (
            f"  Component-marginal (subject-only $-$ comp.-safe) & "
            f"{fmt_ci(cm_w['point_estimate'], cm_w['ci_lo'], cm_w['ci_hi'])} & & & "
            f"{fmt_ci(cm_n['point_estimate'], cm_n['ci_lo'], cm_n['ci_hi'])} & & \\\\"
        ),
        "  \\bottomrule",
        "\\end{tabular}",
        "\\end{table*}",
    ])
    return body


def build_demographics_table() -> str:
    # Build a subject-level DataFrame-ish dict: ptid -> {dx, sex, age_at_baseline_scan, mmse_baseline, ...}
    manifest = list(csv.DictReader(MANIFEST.open()))

    # Map ptid -> set of diagnoses observed across that subject's scans;
    # use the "majority across CN/AD-positive" rule for the demographics table:
    # treat each subject as belonging to the diagnosis group of their primary
    # CN/AD label if any, else MCI, else unknown.
    subj_dx = {}
    subj_sex = {}
    subj_age_first = {}  # earliest acq_date age
    for row in manifest:
        ptid = row["ptid"]
        if not ptid:
            continue
        dx = row["diagnosis_group"]
        prev = subj_dx.get(ptid)
        # Priority: AD > CN > MCI > unknown.
        priority = {"AD": 3, "CN": 2, "MCI": 1, "unknown": 0}
        if (prev is None) or priority.get(dx, 0) > priority.get(prev, 0):
            subj_dx[ptid] = dx
        if row["sex"] and ptid not in subj_sex:
            subj_sex[ptid] = row["sex"]
        if row["age"]:
            try:
                age = float(row["age"])
            except ValueError:
                continue
            cur = subj_age_first.get(ptid)
            acq = row["acq_date"]
            if cur is None or acq < cur[1]:
                subj_age_first[ptid] = (age, acq)

    # Compute baseline MMSE per subject (earliest MMSCORE in MMSE table)
    subj_mmse = {}
    for r in csv.DictReader(MMSE.open()):
        ptid = r.get("PTID", "")
        score = r.get("MMSCORE", "")
        date = r.get("VISDATE", "") or r.get("USERDATE", "")
        if not (ptid and score and date):
            continue
        try:
            s = int(score)
        except ValueError:
            continue
        if s < 0:
            continue  # ADNI uses -4 / -1 sentinels for missing
        cur = subj_mmse.get(ptid)
        if cur is None or date < cur[1]:
            subj_mmse[ptid] = (s, date)

    def summarize(group: str) -> dict:
        ptids = [p for p, dx in subj_dx.items() if dx == group]
        ages = [subj_age_first[p][0] for p in ptids if p in subj_age_first]
        sexes = [subj_sex.get(p, "?") for p in ptids]
        mmses = [subj_mmse[p][0] for p in ptids if p in subj_mmse]
        n_scans = sum(1 for r in manifest if r["ptid"] in ptids)
        n_F = sum(1 for s in sexes if s == "F")
        return {
            "n_subjects": len(ptids),
            "n_scans": n_scans,
            "age_mean": statistics.mean(ages) if ages else 0.0,
            "age_sd": (statistics.stdev(ages) if len(ages) > 1 else 0.0),
            "n_female": n_F,
            "pct_female": (100.0 * n_F / len(ptids) if ptids else 0.0),
            "mmse_mean": statistics.mean(mmses) if mmses else float("nan"),
            "mmse_sd": (statistics.stdev(mmses) if len(mmses) > 1 else 0.0),
        }

    cn = summarize("CN")
    mci = summarize("MCI")
    ad = summarize("AD")
    overall_n_subjects = cn["n_subjects"] + mci["n_subjects"] + ad["n_subjects"]
    overall_n_scans = cn["n_scans"] + mci["n_scans"] + ad["n_scans"]

    def col(s: dict) -> list[str]:
        return [
            f"{s['n_subjects']}",
            f"{s['n_scans']}",
            f"{s['age_mean']:.1f} $\\pm$ {s['age_sd']:.1f}",
            f"{s['n_female']} ({s['pct_female']:.0f}\\%)",
            (f"{s['mmse_mean']:.1f} $\\pm$ {s['mmse_sd']:.1f}"
             if s["mmse_mean"] == s["mmse_mean"] else "n/a"),
        ]

    rows = [
        ["Subjects ($n$)", str(cn["n_subjects"]), str(mci["n_subjects"]),
         str(ad["n_subjects"]), str(overall_n_subjects)],
        ["Scans ($n$)", str(cn["n_scans"]), str(mci["n_scans"]),
         str(ad["n_scans"]), str(overall_n_scans)],
        ["Age, years (mean $\\pm$ SD)",
         f"{cn['age_mean']:.1f} $\\pm$ {cn['age_sd']:.1f}",
         f"{mci['age_mean']:.1f} $\\pm$ {mci['age_sd']:.1f}",
         f"{ad['age_mean']:.1f} $\\pm$ {ad['age_sd']:.1f}",
         "---"],
        ["Female ($n$, \\%)",
         f"{cn['n_female']} ({cn['pct_female']:.0f}\\%)",
         f"{mci['n_female']} ({mci['pct_female']:.0f}\\%)",
         f"{ad['n_female']} ({ad['pct_female']:.0f}\\%)",
         "---"],
        ["Baseline MMSE (mean $\\pm$ SD)",
         (f"{cn['mmse_mean']:.1f} $\\pm$ {cn['mmse_sd']:.1f}" if cn['mmse_mean']==cn['mmse_mean'] else "n/a"),
         (f"{mci['mmse_mean']:.1f} $\\pm$ {mci['mmse_sd']:.1f}" if mci['mmse_mean']==mci['mmse_mean'] else "n/a"),
         (f"{ad['mmse_mean']:.1f} $\\pm$ {ad['mmse_sd']:.1f}" if ad['mmse_mean']==ad['mmse_mean'] else "n/a"),
         "---"],
    ]

    body = "\n".join([
        "% Auto-generated by scripts/generate_adni_paper_tables.py.",
        "% Do not hand-edit; regenerate from the manifest + PTDEMOG + MMSE.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{ADNI1: Complete 3Yr 1.5T cohort demographics. Subject-level "
        "summary; subjects are assigned to a diagnosis group by highest-priority "
        "label observed across all visits (AD $>$ CN $>$ MCI). Age computed at "
        "each subject's earliest scan from \\texttt{PTDOBYY}; baseline MMSE is "
        "each subject's earliest non-missing \\texttt{MMSCORE}.}",
        "\\label{tab:adni_demographics}",
        "\\small",
        "\\begin{tabular}{lrrrr}",
        "  \\toprule",
        "  & \\textbf{CN} & \\textbf{MCI} & \\textbf{AD} & \\textbf{Total} \\\\",
        "  \\midrule",
        *[f"  {r[0]} & {r[1]} & {r[2]} & {r[3]} & {r[4]} \\\\" for r in rows],
        "  \\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])
    return body


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "adni_inflation_gap.tex").write_text(build_inflation_table() + "\n", encoding="utf-8")
    (OUT_DIR / "adni_demographics.tex").write_text(build_demographics_table() + "\n", encoding="utf-8")
    print(f"Wrote {OUT_DIR / 'adni_inflation_gap.tex'}")
    print(f"Wrote {OUT_DIR / 'adni_demographics.tex'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
